# Use Node.js for building Svelte
FROM node:20

WORKDIR /app

# COPY rollup.config.js ./
COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Build the Svelte app
RUN npm run build

# COPY ./src ./src
# COPY ./public ./public
# RUN npm run-script build


# Example from https://github.com/comploplo/svelte-go-docker/blob/main/app/Dockerfile
# install dependencies
# WORKDIR /app

# COPY rollup.config.js ./
# COPY package*.json ./
# RUN npm install

# COPY ./src ./src
# COPY ./public ./public
# RUN npm run-script build

# EXPOSE 5000
# ENV HOST=0.0.0.0
# CMD [ "npm", "run", "dev" ]