version: "3.9"

services:
  db:
    build: ./db
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: heet
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - heet_network  # Network
  
  api:
    build: ./backend
    container_name: go_api_server_container
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: postgres_container
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: heet
    ports:
      - "8080:8080"   # Map port 8080 of host to port 8080 of container
    networks:
      - heet_network  # Network
    
  # Not using/implemented yet
  # web:
  #   build: ./frontend
  #   ports:
  #     - 3000:3000   # Map port 3000 of host to port 3000 of container
      
volumes:
  pg-data: {}

networks:
  heet_network:
    driver: bridge
